MoostBrand - Phase 1/MoostBrand/Controllers/StockTransferDirectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MoostBrand.DAL;
using System.Configuration;
using PagedList;
using MoostBrand.Models;

namespace MoostBrand.Controllers
{
    public class StockTransferDirectsController : Controller
    {
        private MoostBrandEntities entity = new MoostBrandEntities();

        

        #region Action
        // GET: StockTransferDirects
        [AccessCheckerForDisablingButtons(ModuleID = 4)]
        [AccessChecker(Action = 1, ModuleID = 4)]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "stid" : "";


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            //int locID = Convert.ToInt32(Session["locationID"]);
            //int UserID = Convert.ToInt32(Session["userID"]);

            //var user = entity.Users.FirstOrDefault(x => x.ID == UserID);
            var sts = from o in entity.StockTransfers.Where(p => p.StockTransferTypeID == 4)
                      select o;

            if (!String.IsNullOrEmpty(searchString))
            {
                sts = sts.Where(o => o.TransferID.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "reqno":
                    sts = sts.OrderByDescending(o => o.TransferID);
                    break;
                default:
                    sts = sts.OrderBy(o => o.ID);
                    break;
            }

            int pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["pageSize"]);
            int pageNumber = (page ?? 1);

            //if (user.LocationID != 10)
            //{
            //    sts = sts.Where(x => x.LocationID == locID);
            //    return View(sts.ToPagedList(pageNumber, pageSize));
            //}
            //else
            //    return View(sts.ToPagedList(pageNumber, pageSize));

            return View(sts.ToPagedList(pageNumber, pageSize));
        }

        [AccessChecker(Action = 1, ModuleID = 4)]
        public ActionResult Details(int? page, int id = 0)
        {
            var stocktransfer = entity.StockTransfers.Find(id);

            if (stocktransfer == null)
            {
                return HttpNotFound();
            }
            ViewBag.Page = page;
            return View(stocktransfer);
        }

        // GET: StockTransferDirects/Create
        public ActionResult Create(string id)
        {
            var stDirect = new StockTransfer();
            stDirect.STDAte = DateTime.Now;
            stDirect.TransferID = "STR " + Generator(id);

            #region DROPDOWNS
            var items = entity.StockTransferDetails.Where(r => r.RequisitionDetailID != null )
                .ToList()
                .FindAll(r => r.AprovalStatusID == 2)
                .Select(rd => new
                {
                    ID = rd.RequisitionDetail.Item.DescriptionPurchase, //rd.ID,
                    Description = rd.RequisitionDetail.Item.DescriptionPurchase
                });

            var empList = new SelectList((from s in entity.Employees
                                          select new
                                          {
                                              ID = s.ID,
                                              FullName = s.FirstName + " " + s.LastName
                                          }), "ID", "FullName");

            var loc = entity.Locations.Where(x => x.ID != 10)
            .Select(x => new
            {
                ID = x.ID,
                Description = x.Description
            });


            ViewBag.ItemID = new SelectList(items.Where(p=>p.ID == ""), "ID", "Description");
            ViewBag.LocationID = new SelectList(loc, "ID", "Description");
            ViewBag.DestinationID = new SelectList(loc, "ID", "Description");
            ViewBag.ReceivedBy = empList;
            ViewBag.RequestedBy = empList;
            ViewBag.ApprovedBy = empList;
            ViewBag.ReleasedBy = empList;
            ViewBag.CounterCheckedBy = empList;
            ViewBag.PostedBy = empList;
            ViewBag.EncodedBy = empList;
            ViewBag.ApprovedStatus = new SelectList(entity.ApprovalStatus, "ID", "Status");
            #endregion

            return View(stDirect);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StockTransfer stockTransferDirect)
        {

            //string itemname = entity.Items.Find(stockTransferDirect.ItemID).Description;

            var stDirect = entity.StockTransfers.Where(s => s.TransferID == stockTransferDirect.TransferID).ToList();

            if (stDirect.Count() > 0)
            {
                ModelState.AddModelError("", "Stock Transfer ID already exists");
            }
            else
            {
                #region Helper
                foreach (Helper h in stockTransferDirect.Helpers.ToList())
                {
                    try
                    {
                        if (h.DeletedHelper == 1)
                        {
                            stockTransferDirect.Helpers.Remove(h);
                        
                        }

                    }
                    catch
                    {
                        ModelState.AddModelError(string.Empty, "There's an error");
                    }
                }
                #endregion
                #region Operator
                foreach (Operator o in stockTransferDirect.Operators.ToList())
                {
                    try
                    {
                        if (o.DeletedOperator == 1)
                        {
                            stockTransferDirect.Operators.Remove(o);
                        }
                    }
                    catch
                    {
                        ModelState.AddModelError(string.Empty, "There's an error");
                    }
                }
                #endregion
                if (stockTransferDirect.LocationID == stockTransferDirect.DestinationID)
                {
                    ModelState.AddModelError("", "Source location should not be the same with the destination.");
                }
                else
                {

                    //stockTransferDirect.ItemName = itemname;
                    stockTransferDirect.ApprovedStatus = 1;
                    stockTransferDirect.IsSync = false;
                    stockTransferDirect.StockTransferTypeID = 4;

                    entity.StockTransfers.Add(stockTransferDirect);
                    entity.SaveChanges();
                    return RedirectToAction("Index");
                }
            

            }

            #region DROPDOWNS
            var items = entity.StockTransferDetails.Where(r => r.RequisitionDetailID != null)
              .ToList()
              .FindAll(r => r.AprovalStatusID == 2)
              .Select(rd => new
              {
                    ID = rd.RequisitionDetail.Item.DescriptionPurchase, //rd.ID,
                    Description = rd.RequisitionDetail.Item.DescriptionPurchase
              });

            var empList = from s in entity.Employees
                          select new
                          {
                              ID = s.ID,
                              FullName = s.FirstName + " " + s.LastName
                          };


            var loc = entity.Locations.Where(x => x.ID != 10)
            .Select(x => new
            {
                ID = x.ID,
                Description = x.Description
            });

            ViewBag.ItemID = new SelectList(items, "ID", "Description");
            ViewBag.LocationID = new SelectList(loc, "ID", "Description", stockTransferDirect.LocationID);
            ViewBag.DestinationID = new SelectList(loc, "ID", "Description", stockTransferDirect.DestinationID);
            ViewBag.ReceivedBy = new SelectList(empList, "ID", "FullName", stockTransferDirect.ReceivedBy);
            ViewBag.RequestedBy = new SelectList(empList, "ID", "FullName", stockTransferDirect.RequestedBy);
            ViewBag.ApprovedBy = new SelectList(empList, "ID", "FullName", stockTransferDirect.ApprovedBy);
            ViewBag.ReleasedBy = new SelectList(empList, "ID", "FullName", stockTransferDirect.ReleasedBy);
            ViewBag.CounterCheckedBy = new SelectList(empList, "ID", "FullName", stockTransferDirect.CounterCheckedBy);
            ViewBag.PostedBy = new SelectList(empList, "ID", "FullName", stockTransferDirect.PostedBy);
            ViewBag.EncodedBy = new SelectList(empList, "ID", "FullName", stockTransferDirect.EncodedBy);
            ViewBag.ApprovedStatus = new SelectList(entity.ApprovalStatus, "ID", "Status", stockTransferDirect.ApprovedStatus);
            #endregion

            return View(stockTransferDirect);
        }

        // GET: StockTransfer/AddItemPartial/5
        [AccessChecker(Action = 2, ModuleID = 4)]
        public ActionResult AddItemPartial(int id)
        {

            var recID = entity.StockTransfers.Find(id);
            var items = entity.Inventories
                        .ToList()
                        .FindAll(rd => rd.LocationCode == recID.LocationID && rd.InStock > 0)
                        .Select(ed => new

MoostBrand - Phase 1/MoostBrand/Views/StockTransferDirects/AddItemPartial.cshtml
@model MoostBrand.DAL.StockTransferDetail

@*<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css" rel="stylesheet" />*@
@*<script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>*@
@*<script type="text/javascript">
    $(document).ready(function () {

        $('.ddl-item').select2({
            data: null
        });
    });
</script>*@


<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Add Item</h4>
    </div>
    @using (Html.BeginForm("AddItemPartial", "StockTransferDirects", FormMethod.Post, new { id = "addItemPartial" }))
            {
        <div class="modal-body">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-horizontal">
                <div class="form-group">
                    <label class = "control-label col-md-2">Item Name</label>
                    <div class="col-md-8">
                        @{
                           
                                @Html.DropDownList("InventoryID", null,"", htmlAttributes: new { @class = "form-control ddl-item" })
                                @Html.ValidationMessageFor(model => model.InventoryID, "", new { @class = "text-danger" })
                            
                        }
                    </div>
                </div>
            </div>
            <div class="form-horizontal">

                <label id="quantitymsg" class="text-danger col-md-8 col-md-offset-2 no-padding"></label>
                <div class="clearfix"></div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        <input type="text" id="Hidden_Quantity" hidden="hidden" />
                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.InStock, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.InStock, new { htmlAttributes = new { @class = "form-control" , @placeholder = "0", @disabled = true } })
                        @Html.ValidationMessageFor(model => model.InStock, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-8">
                        @Html.TextAreaFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

        </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <input type="submit" id="AddItem" value="Add Item" class="btn btn-green"  />
            </div>
    }
</div><!-- /.modal-content -->

<script>

    $("#AddItem").attr('disabled', 'disabled');
    $("#StockTransferDirects").change(function () {
       
        var val = $("#InventoryID").val();
      
        $.ajax({
            url: '@Url.Action("DisplayComputations", "StockTransferDirects")',
            data: { recID: val },
            type: 'get',
            success: function (data) {
                $("#InStock").val(data.InStock);
                $("#Quantity").val(data.Quantity);
                $("#Hidden_Quantity").val(data.Quantity);
         
            }
        })

     
         
        
    });

    //$('.ddl-item').select2({
    //    data: null
    //});
   

    $('#Quantity').focusout(function () {

        if (parseInt($("#Quantity").val()) <= parseInt($("#Hidden_Quantity").val()) && parseInt($("#Quantity").val()) > 0) {
            var instock = parseInt($('#InStock').val());
            console.log(instock);
            $('#quantitymsg').text('');
        }
        else {

            $('#quantitymsg').text('invalid quantity');
            $("#Quantity").val($("#Hidden_Quantity").val());
        }
    })


    $("#InventoryID").change(function () {
        var val = $("#InventoryID").val();
        
        $.ajax({
            url: '@Url.Action("DisplayComputations", "StockTransferDirects")',
            data: { recID: val },
            type: 'get',
            success: function (data) {
                // $("#Committed").val(data.Committed);
                // $("#Ordered").val(data.Ordered);
                $("#InStock").val(data.InStock);
                $("#Quantity").val(data.Quantity);
                $("#Hidden_Quantity").val(data.Quantity);
                $("#AddItem").removeAttr('disabled');
            }
        })
      
       
    });
</script>

MoostBrand - Phase 1/MoostBrand/Views/StockTransferDirects/Create.cshtml
@model MoostBrand.DAL.StockTransfer

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "StockTransferDirects", FormMethod.Post, new { enctype = "multipart/form-data", id = "editForm" }))
{
    @Html.AntiForgeryToken()

    <div class="panel-heading">
        <h4 class="panel-title">Create Direct Stock Transfer</h4>
        <hr />
    </div>
    <div class="panel-body">

        <div class="form-horizontal">

            <div class="form-group">
                <label class="control-label col-md-2">
                    <small class="text-danger"><span class="symbol required"></span> Required Fields</small>
                </label>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger alert alert-danger" })

            @Html.EditorForModel()

            <div class="form-group">
                <div class="col-md-offset-2 col-md-6">
                    @*<input type="submit" value="Create" class="btn btn-green" />*@
                    <input type="button" onclick="myModal()" value="Create" class="btn btn-green hidden" id="save" />
                    <input type="button" value="Create" class="btn btn-green" id="btnCreate" />
                    <a href='@Url.Action("Index")' class="btn btn-light-orange">
                        Back to List
                    </a>
                </div>
            </div>

        </div>

    </div>

    <div id="SaveWindow" class="modal fade" data-backdrop="static" data-keyboard="false">
        <div id="ShowDialogSave" class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">
                        Would you like to proceed?
                    </h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">CLOSE</button>
                    <button type="submit" class="btn btn-primary" onclick="Submit()" id="save">SUBMIT</button>

                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
}

<script src="~/Scripts/CustomJs.js"></script>
<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script type="text/javascript">
    @*$('#LocationID').change(function () {
        _locID = $('#LocationID').val();
        var url = "/StockTransferDirects/GetLocationCode/";

        $.ajax({
            url: url,
            data: { locID: _locID },
            cache: false,
            type: "POST",
            success: function (data) {
                $.each(data, function (i, val) {
                    $.get("@Url.Action("GenerateSTRNumber", "StockTransferDirects")/STR", null, BindData);
                })
            },
            error: function (reponse) {
                alert("error : " + reponse);
            }
        });
    });*@

    //function BindData(data) {
    //    $("#TransferID").val(data);
    //}

    @*function GetLocationCode(_locID) {
        var url = "/StockTransferDirects/GetLocationCode/";

        $.ajax({
            url: url,
            data: { locID: _locID },
            cache: false,
            type: "POST",
            success: function (data) {
                $.get("@Url.Action("GenerateSTRNumber", "StockTransferDirects")/STR", null, BindData);
                $.get("@Url.Action("GenerateSTRNumber", "StockTransferDirects")/STR - ", null, BindData);
            },
            error: function (reponse) {
                alert("error : " + reponse);
            }
        });
    }*@

    function myModal() {
        $('#SaveWindow').modal('show');
    }

    function Submit() {
        $(document).on("click", "#save", function () {
            $("#editForm").unbind('submit').submit();

        });
    }

    $('#btnCreate').click(function (event) {
        var _variable = Validate();
        if (_variable == "passed") {
            myModal();
        }
        else if (_variable == "Helper")
        { alert("Kindly fill up field/s for Helpers"); }
        else if (_variable == "Operator")
        { alert("Kindly fill up field/s for Operators"); }
        else { alert('kindly fill up required fields'); }

    });

    function Validate() {

        var _passed;
        //txtEmail
        if ($('#StockTransferTypeID').val() == '') {
            $('#StockTransferTypeID').css({ "border": "1px solid red" })
            _passed = '1';

        }
        else if ($('#ReceivingID').val() == '' && $("#StockTransferTypeID").val() == 2) {
            $('#ReceivingID').css({ "border": "1px solid red" })
            _passed = '2';

        }
        else if ($('#RequisitionID').val() == '' && $("#StockTransferTypeID").val() == 1) {
            $('#RequisitionID').css({ "border": "1px solid red" })
            _passed = '3';

        }
        else if ($('#LocationID').val() == '') {
            $('#LocationID').css({ "border": "1px solid red" })
            _passed = '4';

        }
        else if ($('#TransferID').val() == '') {
            $('#TransferID').css({ "border": "1px solid red" })
            _passed = '5';

        }
        else if ($('#STDAte').val() == '') {
            $('#STDAte').css({ "border": "1px solid red" })
            _passed = '6';

        }
        else if ($('#TimeStarted').val() == '') {
            $('#TimeStarted').css({ "border": "1px solid red" })
            _passed = '7';

        }
        else if ($('#TimeFinish').val() == '') {
            $(TimeFinish).css({ "border": "1px solid red" })
            _passed = '8';

        }
        else if ($('#Driver').val() == '') {
            $('#Driver').css({ "border": "1px solid red" })
            _passed = '9';

        }

        else if ($('#PlateNo').val() == '') {
            $('#PlateNo').css({ "border": "1px solid red" })
            _passed = '11';

        }
        else if ($('._helper').val() == '' || $('._helper').val() == null) {
            //$('.helper-field').css({ "border": "1px solid red" })
            _passed = "Helper";
            //alert("Kindly fill up fields for Helper");

        }
        else if ($('#RequestedBy').val() == '') {
            $('#RequestedBy').css({ "border": "1px solid red" })
            _passed = '13';

        }
        else if ($('#ReceivedBy').val() == '') {
            $('#ReceivedBy').css({ "border": "1px solid red" })
            _passed = '14';

        }
        else if ($('#ReleasedBy').val() == '') {
            $('#ReleasedBy').css({ "border": "1px solid red" })
            _passed = '15';

        }
        else if ($('._operator').val() == '' || $('._operator').val() == null) {
            //$('.operator-field').css({ "border": "1px solid red" })
            _passed = "Operator";


        }
            //
        else if ($('#CounterCheckedBy').val() == '') {
            $('#CounterCheckedBy').css({ "border": "1px solid red" })
            _passed = '18';

        }
        else if ($('#EncodedBy').val() == '' ) {
            $('#EncodedBy').css({ "border": "1px solid red" })
            _passed = '19';

        }
        else if ($('#PostedBy').val() == '' ) {
            $('#PostedBy').css({ "border": "1px solid red" })
            _passed = '20';

        }
        else
            _passed = "passed";



        return _passed;

    }



    $('#StockTransferTypeID').change(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#ReceivingID').keyup(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#RequisitionID').keyup(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });

    $('#TimeStarted').change(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#TimeFinish').change(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#LocationID').change(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#TransferID').keyup(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });

    $('#STDAte').change(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#TimeStarted').keyup(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#TimeFinish').keyup(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#Driver').keyup(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#PlateNo').keyup(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#RequestedBy').change(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#ReceivedBy').change(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#ReleasedBy').change(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#CounterCheckedBy').change(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#EncodedBy').change(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#PostedBy').change(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
        if ($(this).val() != '') {
            $(this).css({ "border": "unset" })
        }
    });
    $('#Remarks').keyup(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
    });

    jQuery.validator.unobtrusive.adapters.add("dropdown", function (options) {
        if (options.element.tagName.toUpperCase() == "SELECT" && options.element.type.toUpperCase() == "SELECT-ONE") {
            options.rules["required"] = true;
            if (options.message) {
                options.messages["required"] = options.message;
            }
        }
    });

</script>

