MoostBrand - Phase 1/MoostBrand/Controllers/ColorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MoostBrand.DAL;
using PagedList;
using System.Data.Entity;
using System.Configuration;
using MoostBrand.Models;

namespace MoostBrand.Controllers
{
    public class ColorController : Controller
    {
        MoostBrandEntities entity = new MoostBrandEntities();
        // GET: Colors

        [AccessChecker(Action = 1, ModuleID = 14)]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "code" : "";
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var colors = from c in entity.Colors
                         select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                colors = colors.Where(c => c.Code.Contains(searchString)
                                       || c.Description.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "code":
                    colors = colors.OrderByDescending(c => c.Code);
                    break;
                case "desc":
                    colors = colors.OrderByDescending(c => c.Description);
                    break;
                default:
                    colors = colors.OrderBy(c => c.ID);
                    break;
            }

            int pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["pageSize"]);
            int pageNumber = (page ?? 1);
            return View(colors.ToPagedList(pageNumber, pageSize));
        }

        [AccessChecker(Action = 1, ModuleID = 14)]
        // GET: Color/Details/5
        public ActionResult Details(int id)
        {
            var color = entity.Colors.Find(id);
            return View(color);
        }

        [AccessChecker(Action = 2, ModuleID = 14)]
        // GET: Color/Create
        public ActionResult Create()
        {
            return View();
        }

        [AccessChecker(Action = 2, ModuleID = 14)]
        // POST: Color/Create
        [HttpPost]
        public ActionResult Create(Color color)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    var colorr = entity.Colors.ToList().FindAll(b => b.Code == color.Code);

                    if (colorr.Count() > 0)
                    {
                        ModelState.AddModelError("", "The code already exists.");
                    }
                    else
                    {
                        entity.Colors.Add(color);
                        entity.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                catch
                {
                    ModelState.AddModelError("", "Fill all fields");
                }
            }
            return View(color);
        }

        [AccessChecker(Action = 2, ModuleID = 14)]
        // GET: Color/Edit/5
        public ActionResult Edit(int id)
        {
            var color = entity.Colors.Find(id);
            if (color == null)
                return HttpNotFound();

            return View(color);
        }

        [AccessChecker(Action = 2, ModuleID = 14)]
        // POST: Color/Edit/5
        [HttpPost]
        public ActionResult Edit(Color color)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    entity.Entry(color).State = EntityState.Modified;
                    entity.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ModelState.AddModelError("", "Fill all fields");
                }
            }

            return View(color);
        }

        [AccessChecker(Action = 3, ModuleID = 14)]
        // GET: Color/Delete/5
        public ActionResult Delete(int id = 0)
        {
            var color = entity.Colors.Find(id);
            return View(color);
        }

        [AccessChecker(Action = 3, ModuleID = 14)]
        // POST: Color/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id = 0)
        {
            try
            {
                var color = entity.Colors.Find(id);

                try
                {
                    entity.Colors.Remove(color);
                    entity.SaveChanges();
                }
                catch { }
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MoostBrand - Phase 1/MoostBrand/Views/Color/Create.cshtml
@model MoostBrand.DAL.Color

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel-heading">
        <h4 class="panel-title">Create Color</h4>
        <hr />
    </div>
    <div class="panel-body">

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger alert alert-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-6">
                    <input type="submit" value="Create" class="btn btn-green" />
                    <a href='@Url.Action("Index")' class="btn btn-light-orange">
                        Back to List
                    </a>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>

    $('#Code').keyup(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
    });
    $('#Description').keyup(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
    });
</script>

MoostBrand - Phase 1/MoostBrand/Views/Color/Delete.cshtml
@model MoostBrand.DAL.Color

@{
    ViewBag.Title = "Delete";
}

<div class="panel-heading">
    <h4 class="panel-title">
        Delete Color
        <br /><small>Are you sure you want to delete this?</small>
    </h4>
    <hr />
</div>

<div class="panel-body">
    <div class="form-horizontal">

        <div class="form-group">
            <label class="control-label col-md-2">@Html.DisplayNameFor(model => model.Code)</label>
            <div class="col-md-6">
                <label class="custom-label">
                    @Html.DisplayFor(model => model.Code)
                </label>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">@Html.DisplayNameFor(model => model.Description)</label>
            <div class="col-md-6">
                <label class="custom-label">
                    @Html.DisplayFor(model => model.Description)
                </label>
            </div>
        </div>
        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()

            <div class="form-group">
                <div class="col-md-offset-2 col-md-6">
                    <input type="submit" value="Delete" class="btn btn-red" />
                    <a href='@Url.Action("Index")' class="btn btn-light-orange">
                        Back to List
                    </a>

                </div>
            </div>
        }

    </div>
</div>



MoostBrand - Phase 1/MoostBrand/Views/Color/Details.cshtml
@model MoostBrand.DAL.Color

@{
    ViewBag.Title = "Details";
}

<div class="panel-heading">
    <h4 class="panel-title">Color Details</h4>
    <hr />
</div>

<div class="panel-body">
    <div class="form-horizontal">

        <div class="form-group">
            <label class="control-label col-md-2">@Html.DisplayNameFor(model => model.Code)</label>
            <div class="col-md-6">
                <label class="custom-label">
                    @Html.DisplayFor(model => model.Code)
                </label>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">@Html.DisplayNameFor(model => model.Description)</label>
            <div class="col-md-6">
                <label class="custom-label">
                    @Html.DisplayFor(model => model.Description)
                </label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <a href='@Url.Action("Edit", new { id = Model.ID })' class="btn btn-green">
                    Edit
                </a>
                <a href='@Url.Action("Index")' class="btn btn-light-orange">
                    Back to List
                </a>
            </div>
        </div>


    </div>
</div>



MoostBrand - Phase 1/MoostBrand/Views/Color/Edit.cshtml
@model MoostBrand.DAL.Color

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel-heading">
        <h4 class="panel-title">Edit Color</h4>
        <hr />

    </div>
    <div class="panel-body">

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger alert alert-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-6">
                    <input type="submit" value="Save" class="btn btn-green" />
                    <a href='@Url.Action("Index")' class="btn btn-light-orange">
                        Back to List
                    </a>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>

    $('#Code').keyup(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
    });
    $('#Description').keyup(function () {
        var text = $(this).val();
        $(this).val(text.toUpperCase());
    });
</script>

MoostBrand - Phase 1/MoostBrand/Views/Color/Index.cshtml
@model PagedList.IPagedList<MoostBrand.DAL.Color>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Colors";
}

<div class="panel-heading">
    <h4 class="panel-title">Colors</h4>

</div>
<div class="panel-body">

    <div class="dataTables_wrapper no-footer">
        <div class="dataTables_length">
            <a href="@Url.Action("Create")" class="btn btn-green" style="float:left;"> Create New <i class="fa fa-plus"></i></a>
        </div>
        <div class="dataTables_filter">
            @using (Html.BeginForm("Index", "Color", FormMethod.Post))
            {
                <p>
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control input-sm", @placeholder = "Search" })
                    <input type="submit" value="Search" class="btn btn-green" />
                </p>
            }
            <div class="clearfix"></div>
        </div>

        <div class="clearfix"></div>

    </div>

    <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer">
        <thead>
            <tr>
                <th>
                    @Html.ActionLink("Code", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th>
                    @Html.ActionLink("Description", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        <div class="custom-tools">
                            <a href='@Url.Action("Edit", new { id = item.ID })' class="btn btn-xs btn-blue tooltips" data-placement="top" data-original-title="Edit">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a href='@Url.Action("Details", new { id = item.ID })' class="btn btn-xs btn-green tooltips" data-placement="top" data-original-title="Details">
                                <i class="fa fa-file"></i>
                            </a>
                            <a href='@Url.Action("Delete", new { id = item.ID })' class="btn btn-xs btn-red tooltips" data-placement="top" data-original-title="Delete">
                                <i class="fa fa-times fa fa-white"></i>
                            </a>
                        </div>

                    </td>
                </tr>
            }
        </tbody>
    </table>


    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

</div>