MoostBrand - Phase 1/MoostBrand/Areas/WebService/Models/StockAdjustment.cs
namespace MoostBrand.Areas.WebService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class StockAdjustment
    {
        public int ID { get; set; }

        public int? TransactionTypeID { get; set; }

        public int? ReturnTypeID { get; set; }

        public DateTime? Date { get; set; }

        public int? PreparedBy { get; set; }

        public int? AdjustedBy { get; set; }

        public int? ApprovalStatus { get; set; }

        public int? ApprovedBy { get; set; }

        public string Remarks { get; set; }

        public bool? IsSync { get; set; }
    }
}

MoostBrand - Phase 1/MoostBrand/Areas/WebService/Controllers/StockAdjustmentController.cs
using MoostBrand.Areas.WebService.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web.Http;

namespace MoostBrand.Areas.WebService.Controllers
{
    public class StockAdjustmentController : ApiController
    {
        private MoostBrandEntities db = new MoostBrandEntities();

        // GET: api/StockAdjustment
        public IEnumerable<StockAdjustment> Get()
        {
            return db.StockAdjustments.Where(st => st.IsSync == false);
        }

        // POST: api/StockAdjustment
        public HttpResponseMessage Post(StockAdjustment adjust)
        {
            try
            {
                adjust.IsSync = true;

                db.StockAdjustments.Add(adjust);
                db.SaveChanges();

                return new HttpResponseMessage()
                {
                    Content = new StringContent(
                    "ok",
                    Encoding.UTF8,
                    "text/html"
                )
                };
            }
            catch
            {
            }

            return new HttpResponseMessage()
            {
                Content = new StringContent(
                    "failed",
                    Encoding.UTF8,
                    "text/html"
                )
            };
        }
    }
}

MoostBrand - Phase 1/MoostBrand/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MoostBrand.DAL;
using PagedList;
using System.Data.Entity;
using System.Configuration;
using System.IO;
using MoostBrand.Models;

namespace MoostBrand.Controllers
{
    public class ItemController : Controller
    {
        MoostBrandEntities entity = new MoostBrandEntities();

        private int ID;
        DateTime dt = DateTime.Now; //Robi

        #region METHODS
        //Robi
        private string CodeGenerator()
        {
        //Initiate objects & vars
        startR: Random random = new Random();
            string randomString = "";
            int randNumber = 0;

            //Loop 'length' times to generate a random number or character
            for (int i = 0; i < 8; i++)
            {
                if (i == 0)
                {
                start: randNumber = random.Next(0, 9); //int {0-9}
                    if (randNumber == 0)
                        goto start;
                }
                else
                {
                    randNumber = random.Next(0, 9);
                }
                //append random char or digit to random string
                randomString = randomString + randNumber.ToString();
            }

            //randomString = "M-" + randomString;
            randomString = "M" + dt.ToString("yy") + "-" + randomString;
            var itm = entity.Items.ToList().FindAll(p => p.ItemID == randomString);
            if (itm.Count() > 0)
            {
                goto startR;
            }
            return randomString;
        }

        // [HttpPost]
        //public ActionResult GetSubCategory(int categoryID)
        //{

        //    var objsubcat = entity.SubCategories
        //            .Where(s => s.CategoryID == categoryID)
        //            .Select(s => new { s.ID, s.Description })
        //            .OrderBy(s => s.Description);

        //    return Json(objsubcat, JsonRequestBehavior.AllowGet);
        //}

        [HttpPost]
        public JsonResult GetSubCat(string subcat)
        {
            var _subcat = entity.SubCategories.Distinct().Where(x => (x.Code.Contains(subcat) || x.Description.Contains(subcat)))
                            .Select(x => new
                            {
                                ID = x.ID,
                                SubCategory = x.Description

                            });
            return Json(_subcat, JsonRequestBehavior.AllowGet);
        }

        public void AddTagging(int itemID, int? CategoryID, int TaggedID)
        {
            try
            {

                Item item = entity.Items.Find(itemID);
                item.CategoryID = CategoryID;
                entity.SaveChanges();

                var _header = entity.CategoryTaggings.Where(p => p.CategoryID == CategoryID && p.ItemID == itemID && p.SubCategoryID == TaggedID).FirstOrDefault();

                if (_header == null)
                {
                    CategoryTagging _h = new CategoryTagging();
                    _h.ItemID = itemID;
                    _h.CategoryID = CategoryID.Value;
                    _h.SubCategoryID = TaggedID;
                    entity.CategoryTaggings.Add(_h);
                    entity.SaveChanges();

                }

            }
            catch (Exception e) { e.ToString(); }
        }

        public void DeleteTagging(int? taggedid)
        {
            try
            {
                CategoryTagging details = entity.CategoryTaggings.Find(taggedid);
                entity.CategoryTaggings.Remove(details);
                entity.SaveChanges();

            }
            catch { }
        }


        [HttpPost]
        public ActionResult GetItemById(int itemID)
        {
            var item = entity.Items.FirstOrDefault(i => i.ID == itemID);

            return Json(
                new
                {
                    ID = item.ID,
                    Category = item.CategoryID,
                    SubCategory = item.SubCategoryID

                },
                JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetVendors(string name)
        {
            //x.Name.Contains(name) ||
            var vendors = entity.Vendors.Where(x => x.GeneralName.Contains(name))
                            .Select(x => new
                            {
                                ID = x.ID,
                                Name = x.GeneralName
                            });
            return Json(vendors, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region COMMENTS

        //[HttpPost]
        //public JsonResult IsUniq(string code, string description)
        //{
        //    bool status;
        //    var itm = entity.Items.ToList().FindAll(b => b.Code == code && b.Description == description);

        //    if (itm.Count() > 0)
        //        status = false;
        //    else
        //        status = true;

        //    return new JsonResult { Data = new { status = status } };
        //}

        // GET: Item/Edit/5

        #endregion
        [AccessCheckerForDisablingButtons(ModuleID = 11)]
        [AccessChecker(Action = 1, ModuleID = 11)]
        // GET: Items
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "code" : "";
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var items = from i in entity.Items
                        select i;

            if (!String.IsNullOrEmpty(searchString))
            {
                items = items.Where(i => i.Code.Contains(searchString)
                                       || i.Description.Contains(searchString)
                                      // ||i.Status.Contains(searchString)
                                       || i.DescriptionPurchase.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "code":
                    items = items.OrderByDescending(i => i.Code);
                    break;
                case "desc":
                    items = items.OrderByDescending(i => i.Description);
                    break;
                default:
                    items = items.OrderBy(i => i.ID);
                    break;
            }

            int pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["pageSize"]);
            int pageNumber = (page ?? 1);
            return View(items.ToPagedList(pageNumber, pageSize));
        }

        [AccessChecker(Action = 1, ModuleID = 11)]
        // GET: Item/Details/5
        public ActionResult Details(int id)
        {
            var item = entity.Items.Find(id);
            return View(item);
        }

        [AccessChecker(Action = 2, ModuleID = 11)]
        // GET: Item/Create
        public ActionResult Create()
        {
            //Robi
            var item = new Item();
            item.ItemID = CodeGenerator();

            ViewBag.Categories = entity.Categories.OrderBy(p=>p.Description).ToList();
            ViewBag.Colors = entity.Colors.OrderBy(p => p.Description).ToList();
            ViewBag.Sizes = entity.Sizes.ToList();
            ViewBag.UOMS = entity.UnitOfMeasurements.ToList();
            ViewBag.Brands = entity.Brands.ToList();
            ViewBag.ItemStatus = entity.ItemStatus.ToList();

            return View(item);
       
        }

        [AccessChecker(Action = 2, ModuleID = 11)]
        // POST: Item/Create
        [HttpPost]
        public ActionResult Create(int? selectedSubCatID, int? selectedSubCatTypeID, Item item)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    var itm = entity.Items.ToList().FindAll(b => b.Code == item.Code);
                    //var codecheck = entity.Items.ToList().FindAll(b => b.Description == item.Description);

                    if (item.Proceed == false)
                    {
                        if (itm.Count() > 0)
                        {
                            //  ViewBag.Error = "Would you like to proceed in adding the same items?";
                            ModelState.AddModelError("", "The ItemCode already exists.");
                            ViewBag.Categories = entity.Categories.ToList();
                            ViewBag.Colors = entity.Colors.ToList();
                            ViewBag.Sizes = entity.Sizes.ToList();
                            ViewBag.UOMS = entity.UnitOfMeasurements.ToList();
                            ViewBag.Brands = entity.Brands.ToList();
                            ViewBag.ItemStatus = entity.ItemStatus.ToList();

                            if (selectedSubCatID != null)
                                ViewData["DDLSubCat"] = new SelectList(entity.SubCategories.ToList(), "ID", "Description", selectedSubCatID);
                            else
                                ViewData["DDLSubCat"] = new SelectList(entity.SubCategories.ToList(), "ID", "Description");

                            if (selectedSubCatTypeID != null)
                                ViewData["DDLSubCatType"] = new SelectList(entity.SubCategories.ToList(), "ID", "Description", selectedSubCatTypeID);

MoostBrand - Phase 1/MoostBrand/Views/StockAdjustment/Index.cshtml
@model PagedList.IPagedList<MoostBrand.DAL.StockAdjustment>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Stock Adjustments";
}
<div class="panel-heading">
    <h4 class="panel-title">Stock Adjustments</h4>
</div>
<div class="panel-body">
    <div class="dataTables_wrapper no-footer">
        <div class="dataTables_length">
            <a href="@Url.Action("Create")" class="btn btn-green @Session["canedit"]" style="float:left;"> Create New <i class="fa fa-plus"></i></a>
        </div>
        <div class="dataTables_filter">
            @using (Html.BeginForm("Index", "StockAdjustment", FormMethod.Post))
            {
                <p>
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control input-sm", @placeholder = "Search" })
                    <input type="submit" value="Search" class="btn btn-green" />
                </p>
            }
            <div class="clearfix"></div>
        </div>

        <div class="clearfix"></div>
    </div>

    <form id="action_form">
        @Html.AntiForgeryToken()
        <div class="alert alert-danger">@TempData["Error"]</div>
        <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer">
            <thead>
                <tr>
                    <th>
                        @Html.ActionLink("TransactionType", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink("No", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
            {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TransactionType.Type)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.No)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ApprovalStatu.Status)
                        </td>
                        <td>
                            <div class="custom-tools">
                                <a href='@Url.Action("Details", new { id = item.ID })' class="btn btn-xs btn-green tooltips" data-placement="top" data-original-title="Details">
                                    <i class="fa fa-file"></i>
                                </a>
                                <a href='@Url.Action("Items", new { id = item.ID })' class="btn btn-xs btn-orange tooltips" data-placement="top" data-original-title="Items">
                                    <i class="fa fa-times fa fa-files-o"></i>
                                </a>
                                @if (item.ApprovalStatus == 1)
                                {
                                    //if (Convert.ToInt32(Session["usertype"]) == 1 || Convert.ToInt32(Session["usertype"]) == 4)
                                    //{
                                        <a href='@Url.Action("Edit", new { id = item.ID })' class="btn btn-xs btn-blue tooltips @Session["canedit"]" data-placement="top" data-original-title="Edit">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a href='@Url.Action("Delete", new { id = item.ID })' class="btn btn-xs btn-red tooltips @Session["candelete"]" data-placement="top" data-original-title="Delete">
                                            <i class="fa fa-times fa fa-white"></i>
                                        </a>

                                        <a href="#" id="approve_button" onclick="Approve(@item.ID)" class="btn btn-xs btn-dark-green tooltips @Session["candecide"]" data-placement="top" data-original-title="Approve">
                                            <i class="fa fa-thumbs-up"></i>
                                        </a>
                                        <a href="#" id="deny_button" onclick="Deny(@item.ID)" class="btn btn-xs btn-dark-red tooltips @Session["candecide"]" data-placement="top" data-original-title="Deny">
                                            <i class="fa fa-thumbs-down"></i>
                                        </a>
                                    //}
                                }
                            </div>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>

<div id="DenyWindow" class="modal fade" data-backdrop="static" data-keyboard="false">
    <div id="ShowDialogDeny" class="modal-dialog" role="document">

    </div><!-- /.modal-dialog -->
</div>

<script type="text/javascript">
  

    function Approve() {
        var prID = arguments[0];

        var url = '@Url.Action("Approve", "StockAdjustment")/' + prID;

        var frm = $("#action_form").serialize();
       
        $.post(url, frm);
        location.reload();
    }
    function ReloadFunction() {
        location.reload();
    }

    function Deny(id) {
        @*var prID = arguments[0];

        var url = '@Url.Action("Denied", "StockAdjustment")/' + prID;

        var frm = $("#action_form").serialize();

        $.post(url, frm, ReloadFunction);*@

        var url = '@Url.Action("DenyItemPartial", "StockAdjustment")';
        $.get(url, { id: id }, function (data) {
            $('#ShowDialogDeny').html(data);

            $('#DenyWindow').modal('show');

            // add class form-control to textarea and select
            $("input[disabled]").addClass("form-control");
            $("textarea").addClass("form-control");
            $("select").addClass("form-control");
        });
    }
</script>

MoostBrand - Phase 1/MoostBrand/Views/StockAdjustment/Items.cshtml
@model PagedList.IPagedList<MoostBrand.DAL.StockAdjustmentDetail>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Items";
}
<div class="panel-heading">


    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script>
    $(document).ajaxSuccess(function () {


        $("#catsearch").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '@Url.Action("GetCategories")',
                    type: "POST",
                    dataType: "json",
                    data: { name: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return {
                                id: item.ID,
                                label: item.Name,
                                value: item.Name
                            };
                        }))

                    }
                })
            },
            select: function (event, ui) {
                $("#CategoryID").val(ui.item.id);
                $("#itemcode").val('');
                $("#itemsearch").val('');
            },
            messages: {
                noResults: "", results: ""
            },

        });
        $("#catsearch").autocomplete("option", "appendTo", "#modalCat");

        $("#itemsearch").autocomplete({
            source: function (request, response) {
                var catID = $("#CategoryID").val();
                if(catID == '')
                {
                    catID = '';
                }
                $.ajax({
                    url: '@Url.Action("GetItems")',
                    type: "POST",
                    dataType: "json",
                    data: { catID: catID, name: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return {
                                id: item.ID,
                                label: item.Name,
                                value: item.Name,
                                code: item.Code,
                                category: item.Category
                            };
                        }))

                    }
                })
            },
            select: function (event, ui) {
                $("#ItemID").val(ui.item.id);
                $("#itemcode").val(ui.item.code);
                $("#catsearch").val(ui.item.category);
                Get();

            },
            messages: {
                noResults: "", results: ""
            },

        });
        $("#itemsearch").autocomplete("option", "appendTo", "#modalItem");
        $("#itemsearch").keyup(function () {
            if (!this.value) {
                $('#ItemID').removeAttr('value');
                $('#ItemCode').html('');

            }
        });

        //--------------------- for PUR

        $("#catsearch").autocomplete("option", "appendTo", "#modalCat");



        function Get() {

            var itmID = $("#ItemID").val();
            var itmCode = $("#itemcode").val();

            $.ajax({
                url: "/StockAdjustment/GetOldQuantity",
                type: "POST",
                data: "{'ItemID' : '" + itmID + "'}",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $("#OldQuantity").val(data);
                }

            });


        }

        $("#itemcode").autocomplete({

            source: function (request, response) {
                var catID = $("#CategoryID").val();
                if(catID == '')
                {
                    catID = '';
                }
            
                $.ajax({

                    url: '@Url.Action("GetItemCode")',
                    type: "POST",
                    dataType: "json",
                    data: { catID: catID, name: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return {
                                id: item.ID,
                                label: item.Code,
                                value: item.Code,
                                name: item.Name,
                                category: item.Category
                            };
                        }))
                    }
                })
            },
            select: function (event, ui) {
                $("#itemsearch").val(ui.item.name);
                $("#ItemID").val(ui.item.id);
                $("#ItemCode").val(ui.item.id);
                $("#catsearch").val(ui.item.category);
                Get();
            },
            messages: {
                noResults: "", results: ""
            },

        });
        $("#itemcode").autocomplete("option", "appendTo", "#modalItem");
        $("#itemcode").keyup(function () {
            if (!this.value) {
                $('#ItemID').html('');
                $('#ItemCode').removeAttr('value');
            }
        });


    })
    </script>
    <h4 class="panel-title">Stock Adjustment Items</h4>
    <hr />
</div>
<div class="panel-body">
    <div class="alert alert-danger">@TempData["PartialError"]</div>
    <table class="table table-striped table-bordered table-hover table-full-width dataTable no-footer">
        <thead>
            <tr>
                <th>
                    Item Name
                </th>
                <th>
                    Notes
                </th>
                <th>
                    Old Quantity
                </th>
                <th>
                    New Quantity
                </th>
                <th>
                    Variance
                </th>
                <th>
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.GetItem)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Notes)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OldQuantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NewQuantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Variance)
                    </td>
                    <td>
                        <div class="custom-tools">
                            @if (ViewBag.isApproved == 1)
                            {
                            <a href="#" class="btn btn-xs btn-blue tooltips" data-placement="top" data-original-title="Edit" id="ShowPopopEdit" onclick="ShowEdit(@item.ID)"><i class="fa fa-edit"></i></a>
                            <a href="#" class="btn btn-xs btn-red tooltips" data-placement="top" data-original-title="Delete" id="ShowPopopDelete" onclick="ShowDelete(@item.ID)"><i class="fa fa-times fa fa-white"></i></a>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <br />

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Items",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

    <br /><br />
    @if (ViewBag.isApproved == 1)
    {

        <a href="#" id="ShowPopop" class="btn btn-green">Add Item</a>

    }




    <a href='@Url.Action("Details", new { id = ViewBag.STTAid })' class="btn btn-light-orange">
        Back to Details
    </a>

    <div id="AddItemWindow" class="modal fade" data-backdrop="static" data-keyboard="false" data-url="@Url.Action("AddItemPartial", new { id = ViewBag.STTAid })">
        <div id="ShowDialogAdd" class="modal-dialog" role="document">

        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <div id="EditItemWindow" class="modal fade" data-backdrop="static" data-keyboard="false">
        <div id="ShowDialogEdit" class="modal-dialog" role="document">

        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <div id="DeleteItemWindow" class="modal fade" data-backdrop="static" data-keyboard="false">
        <div id="ShowDialogDelete" class="modal-dialog" role="document">

        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</div>
<script>
    $('#ShowPopop').click(function () {

        var url = $('#AddItemWindow').data('url');
        $.get(url, function (data) {
            $('#ShowDialogAdd').html(data);

            $('#AddItemWindow').modal('show');

            // add class form-control to textarea and select
            $("input[disabled]").addClass("form-control");
            $("textarea").addClass("form-control");
            $("select").addClass("form-control");
        });
    });

    function ShowEdit(id) {
        var url = '@Url.Action("EditItemPartial", "StockAdjustment")/' + id;
        $.get(url, function (data) {
            $('#ShowDialogEdit').html(data);

            $('#EditItemWindow').modal('show');

            // add class form-control to textarea and select
            $("input[disabled]").addClass("form-control");
            $("textarea").addClass("form-control");
            $("select").addClass("form-control");
        });
    }

    function ShowDelete(id) {
        var url = '@Url.Action("DeleteItemPartial", "StockAdjustment")/' + id;
        $.get(url, function (data) {
            $('#ShowDialogDelete').html(data);

            $('#DeleteItemWindow').modal('show');

            // add class form-control to textarea and select
            $("input[disabled]").addClass("form-control");
            $("textarea").addClass("form-control");
            $("select").addClass("form-control");
        });
    }
    function ReloadFunction() {
        location.reload();
    }
    function Approve(id, itemID) {
        var url = '@Url.Action("ApproveItem", "StockAdjustment")/' + id;
        $.post(url, { id: id, itemID: itemID }, ReloadFunction);
    }

    function Deny(id, itemID) {
        var url = '@Url.Action("ApproveItem", "StockAdjustment")/' + id;
        $.post(url, { id: id, itemID: itemID }, ReloadFunction);
    }
</script>